EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'UO_MES'
GO
USE [master]
GO
ALTER DATABASE [UO_MES] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
ALTER DATABASE [UO_MES] SET  SINGLE_USER 
GO
USE [master]
GO
DROP DATABASE [UO_MES]
GO
CREATE DATABASE [UO_MES] ON  PRIMARY 
( NAME = N'UO_MES', FILENAME = N'C:\TEMP\UO_MES.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UO_MES_log', FILENAME = N'C:\TEMP\UO_MES_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [UO_MES] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UO_MES] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UO_MES] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UO_MES] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UO_MES] SET ARITHABORT OFF 
GO
ALTER DATABASE [UO_MES] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UO_MES] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [UO_MES] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UO_MES] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UO_MES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UO_MES] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UO_MES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UO_MES] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UO_MES] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UO_MES] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UO_MES] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UO_MES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UO_MES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UO_MES] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UO_MES] SET  READ_WRITE 
GO
ALTER DATABASE [UO_MES] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [UO_MES] SET  MULTI_USER 
GO
ALTER DATABASE [UO_MES] SET PAGE_VERIFY CHECKSUM  
GO
USE [UO_MES]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [UO_MES] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
