//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "8.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MES() {
        }
        
        /// <summary>
        ///   返回此类使用的、缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MES", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找与 Child Container Level 类似的本地化字符串。
        /// </summary>
        internal static string ChildContainerLevel {
            get {
                return ResourceManager.GetString("ChildContainerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Child Container Name 类似的本地化字符串。
        /// </summary>
        internal static string ChildContainerName {
            get {
                return ResourceManager.GetString("ChildContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Child Qty 类似的本地化字符串。
        /// </summary>
        internal static string ChildQty {
            get {
                return ResourceManager.GetString("ChildQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Child UOM 类似的本地化字符串。
        /// </summary>
        internal static string ChildUOM {
            get {
                return ResourceManager.GetString("ChildUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Close when lot is empty 类似的本地化字符串。
        /// </summary>
        internal static string CloseWhenEmpty {
            get {
                return ResourceManager.GetString("CloseWhenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Combine All Qty 类似的本地化字符串。
        /// </summary>
        internal static string CombineAllQty {
            get {
                return ResourceManager.GetString("CombineAllQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Comment 类似的本地化字符串。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Complete Message 类似的本地化字符串。
        /// </summary>
        internal static string CompleteMessage {
            get {
                return ResourceManager.GetString("CompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Container 类似的本地化字符串。
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Container Information 类似的本地化字符串。
        /// </summary>
        internal static string ContainerInfo {
            get {
                return ResourceManager.GetString("ContainerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Level 类似的本地化字符串。
        /// </summary>
        internal static string ContainerLevel {
            get {
                return ResourceManager.GetString("ContainerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Container Name 类似的本地化字符串。
        /// </summary>
        internal static string ContainerName {
            get {
                return ResourceManager.GetString("ContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Container Status 类似的本地化字符串。
        /// </summary>
        internal static string ContainerStatus {
            get {
                return ResourceManager.GetString("ContainerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Container Step 类似的本地化字符串。
        /// </summary>
        internal static string ContainerStep {
            get {
                return ResourceManager.GetString("ContainerStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Defect Qty 类似的本地化字符串。
        /// </summary>
        internal static string DefectQty {
            get {
                return ResourceManager.GetString("DefectQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Defect Reason 类似的本地化字符串。
        /// </summary>
        internal static string DefectReason {
            get {
                return ResourceManager.GetString("DefectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Disassociate all child lot 类似的本地化字符串。
        /// </summary>
        internal static string DisassociateAll {
            get {
                return ResourceManager.GetString("DisassociateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Due Date 类似的本地化字符串。
        /// </summary>
        internal static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Factory 类似的本地化字符串。
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 From Container Name 类似的本地化字符串。
        /// </summary>
        internal static string FromContainerName {
            get {
                return ResourceManager.GetString("FromContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Hold Reason 类似的本地化字符串。
        /// </summary>
        internal static string HoldReason {
            get {
                return ResourceManager.GetString("HoldReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Language 类似的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Last Status Change Date 类似的本地化字符串。
        /// </summary>
        internal static string LastStatusChangeDate {
            get {
                return ResourceManager.GetString("LastStatusChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Mfg Order 类似的本地化字符串。
        /// </summary>
        internal static string MfgOrder {
            get {
                return ResourceManager.GetString("MfgOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Operation 类似的本地化字符串。
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Product 类似的本地化字符串。
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Qty 类似的本地化字符串。
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Qty Inspected 类似的本地化字符串。
        /// </summary>
        internal static string QtyInspected {
            get {
                return ResourceManager.GetString("QtyInspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Release Reason 类似的本地化字符串。
        /// </summary>
        internal static string ReleaseReason {
            get {
                return ResourceManager.GetString("ReleaseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Resource 类似的本地化字符串。
        /// </summary>
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Resource Info 类似的本地化字符串。
        /// </summary>
        internal static string ResourceInfo {
            get {
                return ResourceManager.GetString("ResourceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Resource Status 类似的本地化字符串。
        /// </summary>
        internal static string ResourceStatus {
            get {
                return ResourceManager.GetString("ResourceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Resource Status Change Reason 类似的本地化字符串。
        /// </summary>
        internal static string ResourceStatusReason {
            get {
                return ResourceManager.GetString("ResourceStatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Setup 类似的本地化字符串。
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Style Theme 类似的本地化字符串。
        /// </summary>
        internal static string StyleTheme {
            get {
                return ResourceManager.GetString("StyleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Thruput all qty 类似的本地化字符串。
        /// </summary>
        internal static string ThruputAllQty {
            get {
                return ResourceManager.GetString("ThruputAllQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 UOM 类似的本地化字符串。
        /// </summary>
        internal static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Work Center 类似的本地化字符串。
        /// </summary>
        internal static string WorkCenter {
            get {
                return ResourceManager.GetString("WorkCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Workflow 类似的本地化字符串。
        /// </summary>
        internal static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Workflow Step 类似的本地化字符串。
        /// </summary>
        internal static string WorkflowStep {
            get {
                return ResourceManager.GetString("WorkflowStep", resourceCulture);
            }
        }
    }
}
