//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MES.
        /// </summary>
        internal static string About_desc {
            get {
                return ResourceManager.GetString("About_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Lot.
        /// </summary>
        internal static string Associate_Lot {
            get {
                return ResourceManager.GetString("Associate_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate multi-lots to a lot.
        /// </summary>
        internal static string Associate_Lot_desc {
            get {
                return ResourceManager.GetString("Associate_Lot_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine Lot.
        /// </summary>
        internal static string Combine_Lot {
            get {
                return ResourceManager.GetString("Combine_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine multi lot into one lot.
        /// </summary>
        internal static string Combine_Lot_desc {
            get {
                return ResourceManager.GetString("Combine_Lot_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Defect.
        /// </summary>
        internal static string Defect_Lot {
            get {
                return ResourceManager.GetString("Defect_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report defect info to a lot.
        /// </summary>
        internal static string Defect_Lot_desc {
            get {
                return ResourceManager.GetString("Defect_Lot_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassociate Lot.
        /// </summary>
        internal static string Disassociate_Lot {
            get {
                return ResourceManager.GetString("Disassociate_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassociate child lot from a lot.
        /// </summary>
        internal static string Disassociate_Lot_desc {
            get {
                return ResourceManager.GetString("Disassociate_Lot_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Lot.
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold a lot.
        /// </summary>
        internal static string Hold_desc {
            get {
                return ResourceManager.GetString("Hold_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Homepage.
        /// </summary>
        internal static string Home_desc {
            get {
                return ResourceManager.GetString("Home_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MES System.
        /// </summary>
        internal static string MES {
            get {
                return ResourceManager.GetString("MES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See our MES system.
        /// </summary>
        internal static string MES_desc {
            get {
                return ResourceManager.GetString("MES_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Out.
        /// </summary>
        internal static string Move_Out {
            get {
                return ResourceManager.GetString("Move_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Out a lot.
        /// </summary>
        internal static string Move_Out_desc {
            get {
                return ResourceManager.GetString("Move_Out_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Txn.
        /// </summary>
        internal static string Move_Txn {
            get {
                return ResourceManager.GetString("Move_Txn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move existing lot to a new step.
        /// </summary>
        internal static string Move_Txn_desc {
            get {
                return ResourceManager.GetString("Move_Txn_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Lot.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release a lot.
        /// </summary>
        internal static string Release_desc {
            get {
                return ResourceManager.GetString("Release_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See out reporting system.
        /// </summary>
        internal static string Report_desc {
            get {
                return ResourceManager.GetString("Report_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Setup.
        /// </summary>
        internal static string ResourceSetup {
            get {
                return ResourceManager.GetString("ResourceSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup a resource status.
        /// </summary>
        internal static string ResourceSetup_desc {
            get {
                return ResourceManager.GetString("ResourceSetup_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Thruput.
        /// </summary>
        internal static string ResourceThruput {
            get {
                return ResourceManager.GetString("ResourceThruput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report the Resource thruput qty.
        /// </summary>
        internal static string ResourceThruput_desc {
            get {
                return ResourceManager.GetString("ResourceThruput_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialize Lot.
        /// </summary>
        internal static string Serialize_Lot {
            get {
                return ResourceManager.GetString("Serialize_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialize a Lot to multi child lot.
        /// </summary>
        internal static string Serialize_Lot_desc {
            get {
                return ResourceManager.GetString("Serialize_Lot_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Lot.
        /// </summary>
        internal static string Split_Lot {
            get {
                return ResourceManager.GetString("Split_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split lot into multi sublot.
        /// </summary>
        internal static string Split_Lot_desc {
            get {
                return ResourceManager.GetString("Split_Lot_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Lot.
        /// </summary>
        internal static string Start_Lot {
            get {
                return ResourceManager.GetString("Start_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start one or more lot.
        /// </summary>
        internal static string Start_Lot_desc {
            get {
                return ResourceManager.GetString("Start_Lot_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thruput Output.
        /// </summary>
        internal static string Thruput {
            get {
                return ResourceManager.GetString("Thruput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report the throughput qty.
        /// </summary>
        internal static string Thruput_desc {
            get {
                return ResourceManager.GetString("Thruput_desc", resourceCulture);
            }
        }
    }
}
