//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UO_ExcelModeler {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResX() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UO_ExcelModeler.ResX", typeof(ResX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutSplash {
            get {
                object obj = ResourceManager.GetObject("AboutSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 delete selection 的本地化字符串。
        /// </summary>
        internal static string Action_DeleteSel {
            get {
                return ResourceManager.GetString("Action_DeleteSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 path destination change 的本地化字符串。
        /// </summary>
        internal static string Action_Dst {
            get {
                return ResourceManager.GetString("Action_Dst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 path creation 的本地化字符串。
        /// </summary>
        internal static string Action_LinkAdd {
            get {
                return ResourceManager.GetString("Action_LinkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 path stretch 的本地化字符串。
        /// </summary>
        internal static string Action_LinkStretch {
            get {
                return ResourceManager.GetString("Action_LinkStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move items 的本地化字符串。
        /// </summary>
        internal static string Action_MoveItems {
            get {
                return ResourceManager.GetString("Action_MoveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 step creation 的本地化字符串。
        /// </summary>
        internal static string Action_NodeAdd {
            get {
                return ResourceManager.GetString("Action_NodeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 step resize 的本地化字符串。
        /// </summary>
        internal static string Action_NodeResize {
            get {
                return ResourceManager.GetString("Action_NodeResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 path origin change 的本地化字符串。
        /// </summary>
        internal static string Action_Org {
            get {
                return ResourceManager.GetString("Action_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 step text change 的本地化字符串。
        /// </summary>
        internal static string Action_Text {
            get {
                return ResourceManager.GetString("Action_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZOrder 的本地化字符串。
        /// </summary>
        internal static string Action_ZOrder {
            get {
                return ResourceManager.GetString("Action_ZOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provide maintain functions for UO-MES object model 的本地化字符串。
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UO-MES Excel Modeler 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;About UO-MES Modeler... 的本地化字符串。
        /// </summary>
        internal static string btnAboutCaption {
            get {
                return ResourceManager.GetString("btnAboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Clean current workbook to Insert status 的本地化字符串。
        /// </summary>
        internal static string btnCleanToInsertCaption {
            get {
                return ResourceManager.GetString("btnCleanToInsertCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Modeler Setting... 的本地化字符串。
        /// </summary>
        internal static string btnSettingCaption {
            get {
                return ResourceManager.GetString("btnSettingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Upload to UO-MES Model 的本地化字符串。
        /// </summary>
        internal static string btnUploadCaption {
            get {
                return ResourceManager.GetString("btnUploadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Workflow Editor... 的本地化字符串。
        /// </summary>
        internal static string btnWorkflowEditorCaption {
            get {
                return ResourceManager.GetString("btnWorkflowEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Clean to Insert Status button 的本地化字符串。
        /// </summary>
        internal static string chkShowCleanToInsertBtnCaption {
            get {
                return ResourceManager.GetString("chkShowCleanToInsertBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Language: 的本地化字符串。
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UO MES Workflow Editor
        ///
        ///Copyright ?2009 UO MES 的本地化字符串。
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;UO-MES Model 的本地化字符串。
        /// </summary>
        internal static string Modeler_menu {
            get {
                return ResourceManager.GetString("Modeler_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UO-MES Excel Modeler Setting 的本地化字符串。
        /// </summary>
        internal static string Modeler_setting {
            get {
                return ResourceManager.GetString("Modeler_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The workflow in the {0} file has changed.
        ///
        ///Do you want to save the changes? 的本地化字符串。
        /// </summary>
        internal static string OkToTrash_Prompt {
            get {
                return ResourceManager.GetString("OkToTrash_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo  的本地化字符串。
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed at {1} 的本地化字符串。
        /// </summary>
        internal static string Service_failed {
            get {
                return ResourceManager.GetString("Service_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} successed at {1} 的本地化字符串。
        /// </summary>
        internal static string Service_success {
            get {
                return ResourceManager.GetString("Service_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} is not defind in CDO {1} 的本地化字符串。
        /// </summary>
        internal static string Type_is_unknown {
            get {
                return ResourceManager.GetString("Type_is_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo  的本地化字符串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled 的本地化字符串。
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UploadSite {
            get {
                object obj = ResourceManager.GetObject("UploadSite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Please save the excel model file first 的本地化字符串。
        /// </summary>
        internal static string Workbook_need_save {
            get {
                return ResourceManager.GetString("Workbook_need_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open a excel model file first 的本地化字符串。
        /// </summary>
        internal static string Workbook_needed {
            get {
                return ResourceManager.GetString("Workbook_needed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap WorkflowEditor {
            get {
                object obj = ResourceManager.GetObject("WorkflowEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
